# Generated by Django 4.2.5 on 2023-09-20 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_campaign_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0055_delete_member_delete_tenant'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Owner',
        ),
    ]
