# Generated by Django 4.2.1 on 2023-09-20 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0002_rename_member_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='', max_length=12)),
                ('date_of_birth', models.DateField()),
                ('relation', models.CharField(max_length=50)),
                ('aniversary_date', models.DateField()),
                ('marital_status', models.CharField(default='Single', max_length=50)),
                ('family_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
