# Generated by Django 4.2.5 on 2023-10-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_owner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'Other')], default='', max_length=12),
        ),
    ]
