# Generated by Django 4.2.5 on 2023-10-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_familymember_gender_alter_tenant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='aniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
