# Generated by Django 4.2.5 on 2023-10-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_familymember_aniversary_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='is_verified',
            new_name='isVerified',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='is_verified',
            new_name='isVerified',
        ),
    ]
