# Generated by Django 4.2.5 on 2023-10-11 10:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0007_rename_is_verified_owner_isverified_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamilyMember',
            new_name='Family',
        ),
    ]
