# Generated by Django 4.2.5 on 2023-10-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_rename_familymember_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner_email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
