# Generated by Django 4.2.5 on 2023-10-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_tenant_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='isVerified_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
