# Generated by Django 4.2.5 on 2023-10-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_owner_isverified_by_owner_owner_owner_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='isVerified_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_otp',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
