# Generated by Django 4.2.5 on 2023-10-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_tenant_isverified_by_owner_tenant_owner_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='isVerified_by_owner',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_otp',
        ),
    ]
