# Generated by Django 4.2.1 on 2024-01-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_remove_owner_isverified_by_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family Member', 'verbose_name_plural': 'Family Members'},
        ),
    ]
