# Generated by Django 4.2.1 on 2024-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_alter_family_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='aniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='marital_status',
            field=models.CharField(default='Single', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='aniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
