# Generated by Django 4.2.1 on 2023-09-22 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('broadcast_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=20)),
                ('committee_role', models.TextField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Package_attributes',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('package_details', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=40)),
                ('no_of_days', models.IntegerField()),
                ('no_of_users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package_Category',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('package_details', models.TextField()),
                ('image_path', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.BooleanField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.package')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.country')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('area_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.city')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('bank_acname', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_acnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='package_rel_attriutes',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Package_attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.package_attributes')),
                ('Package_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.package_category')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.package')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.package_category')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('proceeding', models.TextField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.committee')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('organised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.committee')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.state'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('package_details', models.TextField()),
                ('image_path', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
