# Generated by Django 4.2.5 on 2023-09-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='Payment',
        ),
    ]
