# Generated by Django 4.2.5 on 2023-09-26 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_order_quantity_package_category_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internal.package_category'),
            preserve_default=False,
        ),
    ]
