# Generated by Django 4.2.5 on 2023-09-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0005_alter_order_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
