# Generated by Django 4.2.1 on 2024-01-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=70, null=True),
        ),
    ]
