# Generated by Django 4.2.1 on 2024-01-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0009_productstock_alter_country_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStock',
        ),
    ]
