# Generated by Django 4.2.5 on 2023-09-20 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0053_delete_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('donation_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(default='', max_length=100)),
                ('donation_amount', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
