# Generated by Django 4.2.5 on 2023-10-03 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internal', '0006_alter_order_id'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('donation_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(default='', max_length=100)),
                ('donation_amount', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.owner')),
            ],
        ),
    ]
