# Generated by Django 4.2.5 on 2023-09-20 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.member'),
        ),
    ]
