# Generated by Django 4.2.1 on 2023-06-22 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('', ''), ('M', 'male'), ('F', 'female')], default='', max_length=12)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('res_address', models.CharField(max_length=150)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('', ''), ('M', 'male'), ('F', 'female')], default='', max_length=12)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('res_address', models.CharField(max_length=150)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
