# Generated by Django 4.2.1 on 2023-06-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_res_address_alter_tenant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='res_address',
            field=models.CharField(max_length=150),
        ),
    ]
