# Generated by Django 4.2.1 on 2023-06-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_email_alter_member_res_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='_id',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='supervisor',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='_id',
            new_name='tenant_id',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('donation_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('donation_amount', models.FloatField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
