# Generated by Django 4.2.1 on 2023-06-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_rename__id_member_member_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
    ]
