# Generated by Django 4.2.1 on 2023-06-27 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_rename_donations_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='member_id',
            new_name='member',
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=250)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
