# Generated by Django 4.2.1 on 2023-06-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_rename_member_id_donation_member_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('broadcast_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
