# Generated by Django 4.2.1 on 2023-06-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='committee_role',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='member.committee'),
            preserve_default=False,
        ),
    ]
