# Generated by Django 4.2.1 on 2023-06-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_country_state_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('area_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.city')),
            ],
        ),
    ]
