# Generated by Django 4.2.1 on 2023-07-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_member_user_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='Single', max_length=50),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('', ''), ('M', 'male'), ('F', 'female')], default='', max_length=12)),
                ('relation', models.CharField(max_length=50)),
                ('family_head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
