# Generated by Django 4.2.1 on 2023-07-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_familymember_aniversary_date_familymember_child_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
