# Generated by Django 4.2.1 on 2023-07-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_alter_familymember_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='status',
            new_name='marital_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='committee_role',
        ),
        migrations.AddField(
            model_name='committee',
            name='committee_role',
            field=models.CharField(default='Single', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='phone_no',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='res_hno',
            field=models.SmallIntegerField(),
        ),
    ]
