# Generated by Django 4.2.1 on 2023-07-27 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0019_rename_status_member_marital_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='familymember',
            name='person_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='family_head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
