# Generated by Django 4.2.1 on 2023-07-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_remove_familymember_child_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
    ]
