# Generated by Django 4.2.1 on 2023-07-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_alter_member_res_area_alter_member_res_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='res_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.society'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='res_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.city'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='res_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.country'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='res_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.state'),
        ),
    ]
