# Generated by Django 4.2.1 on 2023-07-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0025_alter_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='res_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.society'),
        ),
        migrations.AlterField(
            model_name='member',
            name='res_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.city'),
        ),
        migrations.AlterField(
            model_name='member',
            name='res_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.country'),
        ),
        migrations.AlterField(
            model_name='member',
            name='res_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='res_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.society'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='res_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='res_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='res_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.state'),
            preserve_default=False,
        ),
    ]
