# Generated by Django 4.2.1 on 2023-07-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_alter_member_res_area_alter_member_res_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='marital_status',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
