# Generated by Django 4.2.1 on 2023-07-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0027_familymember_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='marital_status',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
