# Generated by Django 4.2.1 on 2023-07-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0028_tenant_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='person_name',
        ),
        migrations.AddField(
            model_name='familymember',
            name='fname',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='lname',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
