# Generated by Django 4.2.1 on 2023-07-31 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0029_remove_familymember_person_name_familymember_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='family_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
