# Generated by Django 4.2.1 on 2023-08-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0031_package_package_category_package_attributes_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_attributes',
            name='package',
        ),
    ]
