# Generated by Django 4.2.1 on 2023-08-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0032_remove_package_attributes_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='bundle',
        ),
        migrations.AddField(
            model_name='cart',
            name='package',
            field=models.CharField(default='Not defined', max_length=50),
            preserve_default=False,
        ),
    ]
