# Generated by Django 4.2.1 on 2023-08-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0033_remove_cart_bundle_cart_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package_category',
            old_name='package',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='package_category',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
