# Generated by Django 4.2.1 on 2023-08-10 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0034_rename_package_package_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package_attributes',
            name='package_details',
            field=models.CharField(default='NA', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package_category',
            name='package_details',
            field=models.CharField(default='NA', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='package_rel_attriutes',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Package_attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.package_attributes')),
                ('Package_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.package_category')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.package')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('order_details', models.CharField(max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.package')),
            ],
        ),
        migrations.CreateModel(
            name='billing_history',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('billing_history', models.CharField(max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.package')),
            ],
        ),
    ]
