# Generated by Django 4.2.1 on 2023-08-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0036_remove_payment_payment_method_payment_bank_acname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='marital_status',
            field=models.CharField(default='Single', max_length=50),
        ),
    ]
