# Generated by Django 4.2.1 on 2023-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0037_alter_familymember_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='marital_status',
            field=models.CharField(default='Single', max_length=50),
        ),
    ]
