# Generated by Django 4.2.1 on 2023-08-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0038_alter_familymember_gender_alter_member_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='notes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
