# Generated by Django 4.2.1 on 2023-09-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0040_event_donation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='otp',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
