# Generated by Django 4.2.1 on 2023-09-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0041_member_is_verified_member_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='member',
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='otp',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
