# Generated by Django 4.2.1 on 2023-09-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0042_remove_tenant_member_tenant_is_verified_tenant_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default='2023-09-04 12:00:20.430322'),
            preserve_default=False,
        ),
    ]
