# Generated by Django 4.2.1 on 2023-09-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0043_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_category',
            name='image_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package_category',
            name='package_details',
            field=models.TextField(),
        ),
    ]
