# Generated by Django 4.2.5 on 2023-09-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0046_event_organised_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.committee'),
        ),
    ]
