# Generated by Django 4.2.1 on 2023-09-19 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0047_alter_event_organised_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donation',
            new_name='Campaign',
        ),
        migrations.AddField(
            model_name='committee',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default='1970-01-01 05:30:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='member.committee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='committee_role',
            field=models.TextField(),
        ),
    ]
