# Generated by Django 4.2.5 on 2023-09-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0049_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='minutes_of_meeting',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
