# Generated by Django 4.2.5 on 2023-09-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0050_meeting_minutes_of_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='minutes_of_meeting',
            new_name='proceedings',
        ),
    ]
