# Generated by Django 4.2.5 on 2023-09-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('member', '0051_rename_minutes_of_meeting_meeting_proceedings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='proceedings',
            new_name='proceeding',
        ),
        migrations.AlterField(
            model_name='committee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
