# Generated by Django 4.2.5 on 2023-09-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0052_rename_proceedings_meeting_proceeding_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
