# Generated by Django 4.2.5 on 2023-09-20 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0053_delete_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='res_area',
        ),
        migrations.RemoveField(
            model_name='member',
            name='res_city',
        ),
        migrations.RemoveField(
            model_name='member',
            name='res_country',
        ),
        migrations.RemoveField(
            model_name='member',
            name='res_state',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='res_area',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='res_city',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='res_country',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='res_state',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.AlterField(
            model_name='chat',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
