# Generated by Django 4.2.5 on 2023-09-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_campaign_member'),
        ('member', '0054_remove_member_res_area_remove_member_res_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
