# Generated by Django 4.2.5 on 2023-09-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact_no',
            field=models.IntegerField(max_length=20),
        ),
    ]
