# Generated by Django 4.2.5 on 2023-09-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_ticket_priority_ticket_priority_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketPriority',
        ),
    ]
