# Generated by Django 4.2.5 on 2023-09-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_rename_priority_name_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='Normal', max_length=12),
        ),
    ]
