# Generated by Django 4.2.5 on 2023-09-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_remove_ticket_datetime_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
    ]
