# Generated by Django 4.2.5 on 2023-10-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_ticket_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='contact_no',
            new_name='phone_no',
        ),
    ]
