# Generated by Django 4.2.5 on 2023-10-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_rename_contact_no_ticket_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='resolved',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('pending', 'Pending'), ('opened', 'Opened'), ('reopened', 'Reopened')], default=1, max_length=28),
            preserve_default=False,
        ),
    ]
