# Generated by Django 4.2.5 on 2023-10-09 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('support', '0019_historicalticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='datetime_reply',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='datetime_reply',
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='replied_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
