# Generated by Django 4.2.5 on 2023-09-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salehistory',
            old_name='order_id',
            new_name='order',
        ),
    ]
