# Generated by Django 4.2.5 on 2023-09-21 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0002_rename_order_id_salehistory_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.payment')),
            ],
        ),
    ]
