# Generated by Django 4.2.5 on 2023-09-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_salehistory_quantity_alter_salehistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salehistory',
            name='package',
            field=models.CharField(max_length=250, verbose_name='Package'),
        ),
    ]
