# Generated by Django 4.2.5 on 2023-09-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
