# Generated by Django 4.2.1 on 2024-01-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0009_productstock_alter_country_options_and_more'),
        ('reporting', '0003_alter_paymenthistory_id_alter_productstock_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salehistory',
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='salehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
        migrations.DeleteModel(
            name='SaleHistory',
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('internal.payment',),
        ),
        migrations.CreateModel(
            name='SaleHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Sale History',
                'verbose_name_plural': 'Sale Histories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('internal.order',),
        ),
    ]
