# Generated by Django 4.2.1 on 2024-01-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0010_delete_productstock'),
        ('reporting', '0004_remove_salehistory_payment_remove_salehistory_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='product_name',
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='internal.package_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
